class ClassMap(object):
    def __init__(self):
        self.class_map = {
                      0:"ATL", 
                      1:"CM",
                      2:"PE",
                      3:"CS", 
                      4:"EDMA", 
                      5:"PM",
                      6:"Normal",
                      7:"Enlarged Cardiomediastinum",
                      8:"Fracture",
                      9:"Lung Lesion",
                      10:"Lung Opacity",
                      11:"Pneumothorax",
                      12:"Pleural Other",
                      13:"Support Devices",
                      275:'0.75PE',
                      25:'0.5PE',
                      225:'0.25PE',
                      2125:'0.125PE',
                      20625:'0.0625PE',
                      }
        self.class2index_map = {
                      "ATL":0,
                      "CM":1,
                      "PE":2,
                      "CS":3,
                      "EDMA":4,
                      "PM":5,
                      "Normal":6,
                      "Enlarged Cardiomediastinum":7,
                      "Fracture":8,
                      "Lung Lesion":9,
                      "Lung Opacity":10,
                      "Pneumothorax":11,
                      "Pleural Other":12,
                      "Support Devices":13,
                      }